### ISSUE TITLE
Questions regarding the implementation

### ISSUE THREAD

**Issue by weedwind** [r06944010/Speech-Separation-TF2#1]
Hi, 
Thank you for sharing your implementation. After reading your code, I have a couple of questions. One is that in the clustering part, your code actually implements the Adanet approach proposed in the deep attractor paper, but the the paper (improved source separation...) uses K-means (they claim that it's from deep attractor, but deep attractor does not actually use k-means in Adanet). So did you achieve the paper performance using your implemented method?

Another question is that your mask does not use any nonlinear function, such as sigmoid or softmax, but DAnet actually uses these. Did you try nonlinear functions for the mask?

Thank you so much.

**Comment by r06944010** [comment]
Hi, sorry for not updating sooner.

For the first question (clustering part), we see that the Adanet is actually performing a 1-step K-means clustering, by updating the chosen anchors (centers) once into the speaker-related (in the mixture) embeddings. And of course we have achieve the performance described in the paper.

We have also tested different nonlinear function added after the mask, but it seems that not using any of them can reach the best performance.
